# This Pipeline will manage CloudRun deployment via Terraform

name: 'CICD Pipeline'

on: 
  workflow_dispatch:

  push:
    branches:
      - 'main'
      - 'dev'
      - 'feature/firstbranch'
    paths:
      # This will ensure to kick start wit the deployment if there is any change to these directories.
      - 'infra/**'
      - 'src/**'
      - 'data/**'

concurrency: ${{ github.repository }}

jobs:
  tf_workspace:
    name: 'CICD Job for TF deployment'
    runs-on: 'ubuntu-latest'

    steps:
      - name: GIT Checkout
        id: 'git-checkout'
        uses: "actions/checkout@v4"

      - name: Terraform Init
        id: 'tf-init'
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.secret_json_gcp_key }}
        run: |
          cd ./infra
          terraform init
          pwd

      - name: Terraform Plan
        id: 'tf-plan'
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.SECRET_JSON_GCP_KEY }}
        run: |
          cd ./infra
          terraform plan
          pwd

      - name: Terraform Apply
        id: 'tf-apply'
        if: |
          github.ref == 'refs/heads/main'
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.SECRET_JSON_GCP_KEY }}
        run: |
          cd ./infra
          terraform apply --auto-approve
          pwd

      - name: Set up Google Cloud credentials
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.SECRET_JSON_GCP_KEY }}
        run: echo "$GOOGLE_CREDENTIALS" > $GITHUB_WORKSPACE/cred.json
        shell: bash

      - name: Debug credentials file
        run: |
          echo "Content of cred.json:"
          cat $GITHUB_WORKSPACE/cred.json
          echo "File size:"
          ls -l $GITHUB_WORKSPACE/cred.json
          echo "File content length:"
          wc -c < $GITHUB_WORKSPACE/cred.json

          echo "Generated content With SHA256:"
          sha256sum $GITHUB_WORKSPACE/cred.json

      - name: Validate credentials file
        run: |
          python - <<EOF
          import json
          try:
              with open("${{ github.workspace }}/cred.json", 'r') as file:
                  json.load(file)
              print("Valid JSON")
          except json.JSONDecodeError as e:
              print(f"Invalid JSON: {e}")
              exit(1)
          EOF

      - name: Upload File
        id: 'python-upload'
        # if: success()
        # if: |
        if: success() && |
          github.ref == 'refs/heads/main'
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.SECRET_JSON_GCP_KEY }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/cred.json
        run: |
          cd ./src
          echo -m "$GOOGLE_CREDENTIALS" > $GOOGLE_APPLICATION_CREDENTIALS
          pip install gcloud google-cloud google-cloud-storage 
          python PythonCode/gcsUpload.py
          rm $GOOGLE_APPLICATION_CREDENTIALS
